In [ ]:
import pandas as pd
data = {
    "Age_Group": ["18-25","26-35","36-45","46-60"],
    "Income": [25000,40000,50000,60000]
}
data = pd.DataFrame(data)
data

  Age_Group  Income
0     18-25   25000
1     26-35   40000
2     36-45   50000
3     46-60   60000

In [ ]:
data.apply(list).to_dict()

{'Age_Group': {0: '18-25', 1: '26-35', 2: '36-45', 3: '46-60'},
 'Income': {0: 25000, 1: 40000, 2: 50000, 3: 60000}}

In [ ]:
data.describe()

             Income
count      4.000000
mean   43750.000000
std    14930.394056
min    25000.000000
25%    36250.000000
50%    45000.000000
75%    52500.000000
max    60000.000000

In [ ]:
summary = data.groupby("Age_Group")["Income"].agg(['mean', 'median', 'min', 'max', 'std'])
summary

              mean   median    min    max  std
Age_Group
18-25      25000.0  25000.0  25000  25000  NaN
26-35      40000.0  40000.0  40000  40000  NaN
36-45      50000.0  50000.0  50000  50000  NaN
46-60      60000.0  60000.0  60000  60000  NaN

In [ ]:
summary = data.groupby("Age_Group")["Income"].agg(['mean', 'median', 'min', 'max', 'std'])
summary.apply(list).to_dict()

{'mean': {'18-25': 25000.0,
  '26-35': 40000.0,
  '36-45': 50000.0,
  '46-60': 60000.0},
 'median': {'18-25': 25000.0,
  '26-35': 40000.0,
  '36-45': 50000.0,
  '46-60': 60000.0},
 'min': {'18-25': 25000, '26-35': 40000, '36-45': 50000, '46-60': 60000},
 'max': {'18-25': 25000, '26-35': 40000, '36-45': 50000, '46-60': 60000},
 'std': {'18-25': nan, '26-35': nan, '36-45': nan, '46-60': nan}}

In [ ]:
mean_income = data.groupby("Age_Group")["Income"].mean()
print(mean_income)

Age_Group
18-25    25000.0
26-35    40000.0
36-45    50000.0
46-60    60000.0
Name: Income, dtype: float64

#Task_2:

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/Iris.csv")

In [ ]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
setosa = data[data["Species"] == "Iris-setosa"]
print("Iris-setosa Statistics:\n")
print(setosa.describe())

Iris-setosa Statistics:

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [ ]:
versicolor = data[data["Species"] == "Iris-versicolor"]
print("Iris-versicolor Statistics:\n")
print(versicolor.describe())

Iris-versicolor Statistics:

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [ ]:
virginica = data[data["Species"] == "Iris-virginica"]
print("Iris-virginica Statistics:\n")
print(virginica.describe())

Iris-virginica Statistics:

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [ ]:
for Species in data['Species'].unique():
    print(f"\nStatistics for {Species}:")
    stats=data[data['Species']==Species].describe()
    print(stats)

Statistics for Iris-setosa:
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

Statistics for Iris-versicolor:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

Statistics for Iris-virginica:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000